<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="125864" started-at="2019-09-24T23:25:01Z" finished-at="2019-09-24T23:27:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="125864" started-at="2019-09-24T23:25:01Z" finished-at="2019-09-24T23:27:07Z">
      <class name="com.GmbH.pleApp.TestCases">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="setup" is-config="true" duration-ms="12556" started-at="2019-09-25T01:24:48Z" finished-at="2019-09-25T01:25:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verfiyAddNumbers()[pri:1, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="verfiyAddNumbers" duration-ms="37559" started-at="2019-09-25T01:25:01Z" finished-at="2019-09-25T01:25:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfiyAddNumbers -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="screenshotOnFailure" is-config="true" duration-ms="2" started-at="2019-09-25T01:25:38Z" finished-at="2019-09-25T01:25:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verfiyAddNumbers status=SUCCESS method=TestCases.verfiyAddNumbers()[pri:1, instance:com.GmbH.pleApp.TestCases@3aeaafa6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="FAIL" signature="verfiysubtractNumbers()[pri:2, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="verfiysubtractNumbers" duration-ms="14445" started-at="2019-09-25T01:25:38Z" finished-at="2019-09-25T01:25:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2.00-5.00=-3.00] but found [2.00-5.00=7.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2.00-5.00=-3.00] but found [2.00-5.00=7.00]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.GmbH.pleApp.TestCases.verifyOperations(TestCases.java:76)at com.GmbH.pleApp.TestCases.verfiysubtractNumbers(TestCases.java:24)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfiysubtractNumbers -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="screenshotOnFailure" is-config="true" duration-ms="721" started-at="2019-09-25T01:25:53Z" finished-at="2019-09-25T01:25:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verfiysubtractNumbers status=FAILURE method=TestCases.verfiysubtractNumbers()[pri:2, instance:com.GmbH.pleApp.TestCases@3aeaafa6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="PASS" signature="verfiymultiplNumbers()[pri:3, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="verfiymultiplNumbers" duration-ms="28703" started-at="2019-09-25T01:25:53Z" finished-at="2019-09-25T01:26:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfiymultiplNumbers -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-09-25T01:26:22Z" finished-at="2019-09-25T01:26:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verfiymultiplNumbers status=SUCCESS method=TestCases.verfiymultiplNumbers()[pri:3, instance:com.GmbH.pleApp.TestCases@3aeaafa6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="PASS" signature="verfiyDivNumbers()[pri:4, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="verfiyDivNumbers" duration-ms="28698" started-at="2019-09-25T01:26:22Z" finished-at="2019-09-25T01:26:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfiyDivNumbers -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-09-25T01:26:51Z" finished-at="2019-09-25T01:26:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verfiyDivNumbers status=SUCCESS method=TestCases.verfiyDivNumbers()[pri:4, instance:com.GmbH.pleApp.TestCases@3aeaafa6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="FAIL" signature="verfiyReset()[pri:5, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="verfiyReset" duration-ms="14276" started-at="2019-09-25T01:26:51Z" finished-at="2019-09-25T01:27:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at com.GmbH.pleApp.TestCases.verfiyReset(TestCases.java:43)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfiyReset -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="screenshotOnFailure" is-config="true" duration-ms="554" started-at="2019-09-25T01:27:05Z" finished-at="2019-09-25T01:27:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verfiyReset status=FAILURE method=TestCases.verfiyReset()[pri:5, instance:com.GmbH.pleApp.TestCases@3aeaafa6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="PASS" signature="mandatory()[pri:6, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="mandatory" duration-ms="873" started-at="2019-09-25T01:27:06Z" finished-at="2019-09-25T01:27:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mandatory -->
        <test-method status="PASS" signature="screenshotOnFailure(org.testng.ITestResult)[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="screenshotOnFailure" is-config="true" duration-ms="0" started-at="2019-09-25T01:27:07Z" finished-at="2019-09-25T01:27:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=mandatory status=SUCCESS method=TestCases.mandatory()[pri:6, instance:com.GmbH.pleApp.TestCases@3aeaafa6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.GmbH.pleApp.TestCases@3aeaafa6]" name="tearDown" is-config="true" duration-ms="3162" started-at="2019-09-25T01:27:07Z" finished-at="2019-09-25T01:27:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.GmbH.pleApp.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
